package com.medj.controller;

import com.medj.service.impl.SummaryStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.format.DateTimeFormatter;

@RestController
@RequestMapping("/summary")
public class SummaryController {

    @Autowired
    private SummaryStore summaryStore;

    @GetMapping(value = "/{token}", produces = MediaType.TEXT_HTML_VALUE)
    public ResponseEntity<String> view(@PathVariable String token) {
        return summaryStore.find(token)
                .map(entry -> ResponseEntity.ok(buildHtml(entry)))
                .orElse(ResponseEntity.notFound().build());
    }

    private String buildHtml(SummaryStore.SummaryEntry entry) {
        String formattedDate = entry.generatedAt()
                .format(DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm"));

        String summaryHtml = entry.summary()
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\n", "<br>");

        String avatarLetter = entry.username().substring(0, 1).toUpperCase();
        String username     = entry.username();

        String template = "<!DOCTYPE html>"
            + "<html lang=\"en\"><head>"
            + "<meta charset=\"UTF-8\"/>"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>"
            + "<title>MedJ \u2014 Medical Summary</title>"
            + "<style>"
            + "* { box-sizing: border-box; margin: 0; padding: 0; }"
            + "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f0f4f8; color: #1a202c; min-height: 100vh; }"
            + "header { background: #1e4fa3; color: white; padding: 20px 24px; display: flex; align-items: center; gap: 12px; }"
            + "header h1 { font-size: 1.3rem; font-weight: 700; }"
            + "header span { font-size: 0.85rem; opacity: 0.8; }"
            + ".card { max-width: 680px; margin: 28px auto; background: white; border-radius: 12px; box-shadow: 0 2px 16px rgba(0,0,0,0.08); overflow: hidden; padding: 0 0 24px; }"
            + ".card-header { background: #eef2ff; border-bottom: 2px solid #c7d2fe; padding: 20px 24px; }"
            + ".card-header h2 { font-size: 1rem; color: #3730a3; margin-bottom: 4px; }"
            + ".card-header p  { font-size: 0.85rem; color: #6b7280; }"
            + ".patient-row { display: flex; align-items: center; gap: 12px; padding: 20px 24px 0; }"
            + ".avatar { width: 44px; height: 44px; background: #1e4fa3; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-size: 1.1rem; font-weight: 700; }"
            + ".patient-info h3 { font-size: 1rem; font-weight: 600; }"
            + ".patient-info p  { font-size: 0.8rem; color: #6b7280; }"
            + ".divider { border: none; border-top: 1px solid #e5e7eb; margin: 20px 24px; }"
            + ".section { padding: 0 24px; }"
            + ".section h4 { font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #1e4fa3; margin-bottom: 12px; }"
            + ".summary-text { font-size: 0.92rem; line-height: 1.75; color: #374151; }"
            + ".footer { margin: 24px 24px 0; padding: 12px 16px; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; font-size: 0.75rem; color: #9ca3af; text-align: center; }"
            + "</style></head><body>"
            + "<header><div><h1>MedJ</h1><span>Medical Summary</span></div></header>"
            + "<div class=\"card\">"
            + "<div class=\"card-header\"><h2>Patient Medical Summary</h2><p>Generated on " + formattedDate + "</p></div>"
            + "<div class=\"patient-row\"><div class=\"avatar\">" + avatarLetter + "</div>"
            + "<div class=\"patient-info\"><h3>" + username + "</h3><p>Patient</p></div></div>"
            + "<hr class=\"divider\"/>"
            + "<div class=\"section\"><h4>Summary</h4><div class=\"summary-text\">" + summaryHtml + "</div></div>"
            + "<div class=\"footer\">This document is auto-generated by MedJ and is for informational purposes only.</div>"
            + "</div></body></html>";

        return template;
    }
}
