spring.application.name=MedJ

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/MEDj
spring.datasource.username=postgres
spring.datasource.password=198576
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.example=debug

spring.web.resources.add-mappings=true
spring.web.resources.static-locations=file:./static/

jwt.privateKeyPath=./key/private.key
jwt.publicKeyPath=./key/public.key

cors.allowed.origins = http://localhost:5173


server.address=0.0.0.0
app.base-url=http://192.168.100.15:8080

google.cloud.project-id=medj-ocr-490912
google.cloud.location=us-central1
gemini.model=gemini-2.5-flash
google.credentials.path=D:/DOWNLOAD/medj-ocr-490912-3a416ab66189.json