spring.application.name=MedJ

spring.jpa.hibernate.ddl-auto=update

#For local tests
#spring.datasource.url=jdbc:postgresql://localhost:5432/MEDj
#spring.datasource.username=postgres
#spring.datasource.password=198576
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
server.address=0.0.0.0

logging.level.org.example=debug

spring.web.resources.add-mappings=true
spring.web.resources.static-locations=file:./static/


jwt.privateKeyPath=./key/private.key
jwt.publicKeyPath=./key/public.key

cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

app.base-url=${APP_BASE_URL:http://localhost:8080}

google.cloud.project-id=medj-ocr-490912
google.cloud.location=us-central1
gemini.model=gemini-2.5-flash
google.credentials.path=${GOOGLE_CREDENTIALS_PATH:/etc/secrets/google-credentials.json}

#For local tests
#google.credentials.path=D:/DOWNLOAD/medj-ocr-490912-3a416ab66189.json